-- MySQL Script generated by MySQL Workbench
-- Wed May 24 01:29:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema app_biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema app_biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app_biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `app_biblioteca` ;

-- -----------------------------------------------------
-- Table `app_biblioteca`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_biblioteca`.`autores` (
  `id_autor` INT NOT NULL AUTO_INCREMENT,
  `nombre_autor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_biblioteca`.`bibliotecas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_biblioteca`.`bibliotecas` (
  `cp_biblioteca` INT NOT NULL,
  `nombre_biblioteca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cp_biblioteca`),
  INDEX `nombre_biblioteca` USING BTREE (`nombre_biblioteca`) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_biblioteca`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_biblioteca`.`categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_biblioteca`.`documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_biblioteca`.`documentos` (
  `isbn` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `replicas` INT NOT NULL DEFAULT 1,
  `biblioteca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`isbn`, `biblioteca`),
  INDEX `fk_documentos_bibliotecas1_idx` (`biblioteca` ASC) VISIBLE,
  CONSTRAINT `fk_documentos_bibliotecas1`
    FOREIGN KEY (`biblioteca`)
    REFERENCES `app_biblioteca`.`bibliotecas` (`nombre_biblioteca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_biblioteca`.`documentos_has_autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_biblioteca`.`documentos_has_autores` (
  `documentos_isbn` INT NOT NULL,
  `autores_id_autor` INT NOT NULL,
  PRIMARY KEY (`documentos_isbn`, `autores_id_autor`),
  INDEX `fk_documentos_has_autores_autores1_idx` (`autores_id_autor` ASC) VISIBLE,
  INDEX `fk_documentos_has_autores_documentos_idx` (`documentos_isbn` ASC) VISIBLE,
  CONSTRAINT `fk_documentos_has_autores_documentos`
    FOREIGN KEY (`documentos_isbn`)
    REFERENCES `app_biblioteca`.`documentos` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_has_autores_autores1`
    FOREIGN KEY (`autores_id_autor`)
    REFERENCES `app_biblioteca`.`autores` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_biblioteca`.`documentos_has_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_biblioteca`.`documentos_has_categorias` (
  `documentos_isbn` INT NOT NULL,
  `categorias_id_categoria` INT NOT NULL,
  PRIMARY KEY (`documentos_isbn`, `categorias_id_categoria`),
  INDEX `fk_documentos_has_categorias_categorias1_idx` (`categorias_id_categoria` ASC) VISIBLE,
  INDEX `fk_documentos_has_categorias_documentos1_idx` (`documentos_isbn` ASC) VISIBLE,
  CONSTRAINT `fk_documentos_has_categorias_documentos1`
    FOREIGN KEY (`documentos_isbn`)
    REFERENCES `app_biblioteca`.`documentos` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_has_categorias_categorias1`
    FOREIGN KEY (`categorias_id_categoria`)
    REFERENCES `app_biblioteca`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_biblioteca`.`grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_biblioteca`.`grupos` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `nombre_grupo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_grupo`),
  INDEX `nombre_grupo` USING BTREE (`nombre_grupo`) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_biblioteca`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_biblioteca`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NULL,
  `baneado` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id_usuario`, `rol`),
  INDEX `fk_usuarios_grupos1_idx` (`rol` ASC) INVISIBLE,
  INDEX `usuario` USING BTREE (`usuario`) VISIBLE,
  CONSTRAINT `fk_usuarios_grupos1`
    FOREIGN KEY (`rol`)
    REFERENCES `app_biblioteca`.`grupos` (`nombre_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_biblioteca`.`prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_biblioteca`.`prestamos` (
  `id_prestamo` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `isbn` INT NOT NULL,
  `fecha_prestamo` DATE NOT NULL,
  `fecha_devolucion` DATE NOT NULL,
  `dias_retardo` INT NULL,
  PRIMARY KEY (`id_prestamo`, `usuario`, `isbn`),
  INDEX `fk_prestamos_usuarios1_idx` (`usuario` ASC) VISIBLE,
  INDEX `fk_prestamos_documentos1_idx` (`isbn` ASC) VISIBLE,
  CONSTRAINT `fk_prestamos_usuarios1`
    FOREIGN KEY (`usuario`)
    REFERENCES `app_biblioteca`.`usuarios` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamos_documentos1`
    FOREIGN KEY (`isbn`)
    REFERENCES `app_biblioteca`.`documentos` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_biblioteca`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_biblioteca`.`reservas` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `isbn` INT NOT NULL,
  `fecha_reserva` DATE NOT NULL,
  `dias_pendientes` INT NOT NULL,
  PRIMARY KEY (`id_reserva`, `usuario`, `isbn`),
  INDEX `fk_reservas_usuarios1_idx` (`usuario` ASC) VISIBLE,
  INDEX `fk_reservas_documentos1_idx` (`isbn` ASC) VISIBLE,
  CONSTRAINT `fk_reservas_usuarios1`
    FOREIGN KEY (`usuario`)
    REFERENCES `app_biblioteca`.`usuarios` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservas_documentos1`
    FOREIGN KEY (`isbn`)
    REFERENCES `app_biblioteca`.`documentos` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_biblioteca`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_biblioteca`.`comentarios` (
  `id_comentarios` INT NOT NULL AUTO_INCREMENT,
  `isbn` INT NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `optinion` VARCHAR(200) NULL,
  PRIMARY KEY (`id_comentarios`, `isbn`, `usuario`),
  INDEX `fk_comentarios_documentos1_idx` (`isbn` ASC) VISIBLE,
  INDEX `fk_comentarios_usuarios1_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_documentos1`
    FOREIGN KEY (`isbn`)
    REFERENCES `app_biblioteca`.`documentos` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`usuario`)
    REFERENCES `app_biblioteca`.`usuarios` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_biblioteca`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_biblioteca`.`libros` (
  `isbn` INT NOT NULL,
  `editorial` VARCHAR(45) NOT NULL,
  `npaginas` INT NOT NULL,
  `tematica` VARCHAR(45) NULL,
  PRIMARY KEY (`isbn`),
  INDEX `fk_libros_documentos1_idx` (`isbn` ASC) VISIBLE,
  CONSTRAINT `fk_libros_documentos1`
    FOREIGN KEY (`isbn`)
    REFERENCES `app_biblioteca`.`documentos` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_biblioteca`.`peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_biblioteca`.`peliculas` (
  `isbn` INT NOT NULL,
  `director` VARCHAR(45) NOT NULL,
  `actores` VARCHAR(45) NOT NULL,
  `premios` VARCHAR(45) NULL,
  `duracion` DECIMAL NOT NULL,
  `formato` VARCHAR(45) NULL,
  PRIMARY KEY (`isbn`),
  INDEX `fk_peliculas_documentos1_idx` (`isbn` ASC) VISIBLE,
  CONSTRAINT `fk_peliculas_documentos1`
    FOREIGN KEY (`isbn`)
    REFERENCES `app_biblioteca`.`documentos` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_biblioteca`.`documentales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_biblioteca`.`documentales` (
  `isbn` INT NOT NULL,
  `productora` VARCHAR(45) NOT NULL,
  `premios` VARCHAR(45) NULL,
  `doc_relacionados` VARCHAR(45) NULL,
  `duracion` DECIMAL NOT NULL,
  `formato` VARCHAR(45) NULL,
  PRIMARY KEY (`isbn`),
  INDEX `fk_documentales_documentos1_idx` (`isbn` ASC) VISIBLE,
  CONSTRAINT `fk_documentales_documentos1`
    FOREIGN KEY (`isbn`)
    REFERENCES `app_biblioteca`.`documentos` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_biblioteca`.`musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_biblioteca`.`musica` (
  `isbn` INT NOT NULL,
  `lugar` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `duracion` DECIMAL NOT NULL,
  `formato` VARCHAR(45) NULL,
  PRIMARY KEY (`isbn`),
  INDEX `fk_musica_documentos1_idx` (`isbn` ASC) VISIBLE,
  CONSTRAINT `fk_musica_documentos1`
    FOREIGN KEY (`isbn`)
    REFERENCES `app_biblioteca`.`documentos` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
